---
- name: "Deploying Website on LAMP stack"
  become: true
  hosts: amazon
  vars_files:
    - variables.yml
  tasks:
    - name: "Package Installation"
      yum:
        name: httpd
        state: present
    - name: "Enabling PHP support"
      shell: amazon-linux-extras install php7.4 -y

    - name: "Creating httpd.conf file"
      template:
        src: ./httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf
        owner: "{{ owner }}"
        group: "{{ group }}"
      notify:
        - apache-reload

    - name: "Creating VirtualHost {{ domain }}"
      template:
        src: "./virtualhost.conf.tmpl"
        dest: "/etc/httpd/conf.d/{{ domain }}.conf"
        owner: "{{ owner }}"
        group: "{{ group }}"
      notify:
        - apache-reload

    - name: "Creating DocumentRoot /var/www/html/{{ domain }}"
      file:
        path: "/var/www/html/{{ domain }}"
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"

    
    - name: "Creating Sample index.html and test.php page under  /var/www/html/{{ domain }}"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ domain }}/"
        owner: "{{ owner }}"
        group: "{{ group }}"
      with_items:
        - index.html
        - test.php
      notify:
        - apache-restart

  handlers:
    - name: "apache-reload"
      service:
        name: httpd
        state: reloaded
        enabled: true
    - name: "apache-restart"
      service:
        name: httpd
        state: restarted
        enabled: true
