---
- name: "Deploying Website on LAMP stack"
  become: true
  hosts: amazon
  vars_files:
    - variables.yml
  tasks:
    - name: "Package Installation"
      yum:
        name: httpd
        state: present
    - name: "Enabling PHP support"
      shell: amazon-linux-extras install php7.4 -y

    - name: "Creating httpd.conf file"
      template:
        src: ./httpd.conf.tmpl
        dest: /etc/httpd/conf/httpd.conf
        owner: "{{ owner }}"
        group: "{{ group }}"
      notify:
        - apache-reload

    - name: "Creating VirtualHost {{ domain }}"
      template:
        src: "./virtualhost.conf.tmpl"
        dest: "/etc/httpd/conf.d/{{ domain }}.conf"
        owner: "{{ owner }}"
        group: "{{ group }}"
      notify:
        - apache-reload

    - name: "Creating DocumentRoot /var/www/html/{{ domain }}"
      file:
        path: "/var/www/html/{{ domain }}"
        state: directory
        owner: "{{ owner }}"
        group: "{{ group }}"

    
    - name: "Creating Sample index.html and test.php page under  /var/www/html/{{ domain }}"
      copy:
        src: "{{ item }}"
        dest: "/var/www/html/{{ domain }}/"
        owner: "{{ owner }}"
        group: "{{ group }}"
      with_items:
        - index.html
        - test.php
      notify:
        - apache-restart

    - name: "Installing Mariadb"    
      yum:                          
        name:                       
          - mariadb-server          
          - MySQL-python            
        state: present
   
    - name: "ReStarting and enabling MariaDB service"
      service:
        name: mariadb
        state: restarted
        enabled: true

    - name: "MariaDB -updating root password"
      ignore_errors: true
      mysql_user:
        login_user: "root"
        login_password: ""
        name: "root"
        password: "{{ mariadb_root_pass }}"
        host_all: true

    - name: "Remove anonymous Users"
      mysql_user:
        login_user: "root"
        login_password: "{{ mariadb_root_pass }}"
        name: ""
        password: ""
        host_all: true
        state: absent 

    - name: "Create a new database for wordpress "
      mysql_db:
        login_user: "root"
        login_password: "{{ mariadb_root_pass }}"
        name: "{{ db_name }}"
        state: present
  
    - name: "Create a new database user"
      mysql_user:
        login_user: "root"
        login_password: "{{ mariadb_root_pass }}"
        name: "{{ db_user }}"
        password: "{{ db_password }}"
        state: present
        host: "%"
        priv: "{{ db_name }}.*:ALL"

    - name: "Final - Restart"
      service:
        name: "{{ item }}"
        state: restarted
        enabled: true
      with_items:
        - httpd
        - mariadb

    - name: "Display mysql datadirectory"
      shell: "grep -i datadir /etc/my.cnf"
      register: output
    - debug:
        var: output.stdout_lines

  handlers:
    - name: "apache-reload"
      service:
        name: httpd
        state: reloaded
        enabled: true
    - name: "apache-restart"
      service:
        name: httpd
        state: restarted
        enabled: true
